name: id_details_extractor
description: A Flutter project to extract ID details  from an ID image.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.5.0"


dependencies:
  flutter:
    sdk: flutter

  #Google Machine learning Text Recognition package
  #This package is used to recognise text from images using Machine learning
  google_mlkit_text_recognition: ^0.4.0

  #Functional programming package 
  fpdart: ^0.2.0

  #Image picker is a package used to select an Image from the file system
  image_picker: ^0.8.5+3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  